# Generated by Django 3.2 on 2024-11-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0003_informe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='last_login',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('jefe_bodega', 'Jefe de Bodega'), ('bodeguero', 'Bodeguero')], max_length=50),
        ),
    ]
