# Generated by Django 3.2 on 2024-11-08 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Aplicacion', '0004_auto_20241108_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informe',
            old_name='fecha_creacion',
            new_name='fecha_envio',
        ),
        migrations.AlterField(
            model_name='informe',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
