# Generated by Django 3.2 on 2024-11-08 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Aplicacion', '0005_auto_20241108_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informe',
            name='fecha_envio',
        ),
        migrations.AlterField(
            model_name='informe',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='informe',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
