# Generated by Django 3.2 on 2024-11-08 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Aplicacion', '0006_auto_20241108_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='informe',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='informe',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='informe',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
