# Generated by Django 3.2 on 2024-11-15 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0009_auto_20241115_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorial',
            name='anio_fundacion',
            field=models.IntegerField(),
        ),
    ]
