# Generated by Django 3.2 on 2024-11-16 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0010_alter_editorial_anio_fundacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='genero',
        ),
        migrations.AddField(
            model_name='libro',
            name='generos',
            field=models.ManyToManyField(to='Aplicacion.Genero'),
        ),
    ]
